# Generated by Django 4.2.1 on 2024-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('product', models.CharField(choices=[('Mobile 1', 'Mobile 1'), ('Mobile 2', 'Mobile 2'), ('Mobile 3', 'Mobile 3')], max_length=20)),
                ('enquiry_message', models.TextField(max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
